### ISSUE TITLE
マイク入力のPermissionダイアログの作成

### ISSUE THREAD

**Issue by pannpers** [pannpers/hitorec#23]
# Overview
ブラウザ上で動作するJavaScriptから『マイク入力』を行う際に、初回のみ『マイクアクセスの許可を求めるプロンプト』が表示される。（下記動画を参照）
https://drive.google.com/file/d/19WBOofw_oBKnKKwy7_hlq8Qf-qEMAV7Z/view?usp=sharing

ユーザーがこのプロンプトで『ブロック』を選択してしまうと、『hitocoto.appではマイク入力を許可しない』という情報が残り続けてしまう。この設定は一応、解除することができるが、ブラウザの設定画面を開かなければならず、 **一般のユーザーはほぼ離脱してしまう** ことが予想される。（下記動画はChromeでPermission設定を解除する手順）

https://drive.google.com/file/d/19SbVMhj_rMdY3-h5v8twRwa9AfM4HH_i/view?usp=sharing

そこで、ブラウザのPermissionの確認プロンプトを表示する前に、hitocotoアプリ側で説明用のダイアログを見せるようにしたい。↓↓こちらはイメージ。

https://www.pinterest.com/pin/502995852115804847/?autologin=true

# To-Do

- [x] マイク入力の許可を求めるダイアログのUIデザイン
- [x] 上記ダイアログの実装

# Notes
参考情報

- [パーミッションの UX  \|  Web Fundamentals  \|  Google Developers](https://developers.google.com/web/fundamentals/push-notifications/permission-ux?hl=ja)
- [モバイルアプリの効果的なアクセス許可要求のためにデザインで考慮すべき3つのこと – U\-Site](https://u-site.jp/alertbox/permission-requests)
- [ユーザーが許可したくなるPush通知を考える｜MAMORU KIJIMA｜note](https://note.com/sadako_a_/n/ncf303d36b658)

**Comment by sugiosugio** [comment]
<img width="321" alt="スクリーンショット 2020-03-30 15 23 50" src="https://user-images.githubusercontent.com/58411645/77881727-8596bd00-729a-11ea-8490-227febd81af9.png">

ダイアログは上記のような要素＆デザインで行こうと思います！
こちらの進め方についてはどのようにしましょうか？
できればフォントサイズやマージンなどの調整はこちらでしたいと思いますが、
どのような分担が進めやすいでしょうか？？

**Comment by pannpers** [comment]
@sugiosugio こちらも同様にHTMLとCSSをスギオさん、JavaScriptで書くBehavior のところをにお任せできればと！

**Comment by sugiosugio** [comment]
@pannpers 

こちらも了解です！
テスト的にダイアログ表示のためのリンクなどを設けて、押下時にダイアログが表示されるような形にしておきます。
