### ISSUE TITLE
確認画面のURLについて　※audition→confirmに変更

### ISSUE THREAD

**Issue by sugiosugio** [pannpers/hitorec#41]
https://hitorec.app/audition

確認画面のURLが現状上記のようになっていますが、
「audition＝試聴」のニュアンスに少々違和感を感じますので、
翻訳者の友人と相談の上、URL別案を考えてみたいと思います〜。
候補決まり次第共有いたします！

**Comment by sugiosugio** [comment]
相談しました！！
やはり「confirm」がもっとも無難とのことなので、
こちらに変更お願いします。

**Comment by pannpers** [comment]
@sugiosugio 修正完了です！
ちなみにHTMLの `<header> > <title>` に表示される文言は↓↓この `app.ts` の `title` という箇所で変更可能ですので、もし修正したいと思ったときはスギオさんの方で修正して頂いてもOKです！
https://github.com/pannpers/hitorec/blob/master/src/app.ts#L24-L30
