### ISSUE TITLE
Twitterログイン前のフッタメニューの挙動について

### ISSUE THREAD

**Issue by sugiosugio** [pannpers/hitorec#53]
現状フッタメニュー（hitoRecについて／利用規約）は、
Twitterログインしないと遷移できない仕様になってますか？？
上記の2コンテンツはログインしなくても見れるべきページなので、
遷移できるように変更お願いします〜。

**Comment by pannpers** [comment]
@sugiosugio 見つけてもらってありがとうございます！
確かにその2つのページは未ログイン状態でも見れるべきなので、Publicに変更しておきました！
